config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  devise_for :users
  root to: "pages#home"
  get '/profile', to: 'pages#profile', as: :profile_path

  resources :rooms, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create, :show]
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one :review
  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :room, through: :booking
  validates :rating, :comment, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :number, presence: true, uniqueness: true
  validates :price_per_night, presence: true
  validates :description, presence: true
  validates :surface, presence: true
  validates :capacite, presence: true
  validates :image_url, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["description", "number"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :prenom, presence: true
  validates :nom, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_query

  def set_query
    @query = Room.ransack(params[:q])
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:prenom, :nom])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:prenom, :nom])
  end

  def after_sign_in_path_for(resource)
    rooms_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(
      start_date: Date.parse(params[:booking][:start_date].split(" au ").first),
      end_date: Date.parse(params[:booking][:start_date].split(" au ").last),
      room: @room,
      user: current_user
    )
    @booking.total_price = ((@booking.end_date - @booking.start_date)+1) * Rational(@room.price_per_night)
    if @booking.save
      redirect_to profile_path_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @room = Room.find(params[:room_id])
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    room = @booking.room
    @booking.destroy!
    redirect_to profile_path_url
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def profile
    @current_bookings = current_user.bookings.where('start_date >= ? AND end_date >= ?', Date.today, Date.today)
    @coming_bookings = current_user.bookings.where('start_date > ?', Date.today)
    @passed_bookings = current_user.bookings.where('end_date < ?', Date.today)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @booking.user = current_user
      if @review.save
        redirect_to room_path(@review.room)
      else
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :booking)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Room.ransack(params[:q])
    @rooms = @query.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<p>Chambre n°<%= @booking.room.number %></p>
<p>Réservée du <%= @booking.start_date %> au <%= @booking.end_date %> </p>
<p>Prix total: <%= @booking.total_price %>€</p>

<%= link_to "Annuler cette réservation", booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer cette réservation?"}, class: 'text-danger' %>
<%= link_to "Retourner aux chambres", rooms_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotelbooking</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/airbnb.css">
    <%= favicon_link_tag asset_path("house.ico"), rel: "icon", type: "image/ico" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="pic-row">
    <%= image_tag "image1.jpg" %>
    <%= image_tag "image2.jpg" %>
  </div>
  <h1>Roomie</h1>
  <div class="pic-row">
    <%= image_tag "image3.jpg" %>
    <%= image_tag "image4.jpg" %>
  </div>
  <div class="btn-row">
    <%= link_to "Se connecter", new_user_session_path %>
    <%= link_to "S'inscrire", new_user_registration_path %>
  </div>

app/views/pages/profile.html.erb
<h1>Réservation en cours</h1>
<% @current_bookings.each do |booking| %>
  <div class="booking-card">
    <h2>Chambre n°<%= booking.room.number %></h2>
    <p>Réservée du <%= booking.start_date %> au <%= booking.end_date %> </p>
    <p>Prix total: <%= booking.total_price %>€</p>
    <%= link_to "Annuler cette réservation", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer cette réservation?"}, class: 'text-danger' %>
  </div>
<% end %>

<h1>Mes réservations à venir</h1>
<% @coming_bookings.each do |booking| %>
  <div class="booking-card">
    <h2>Chambre n°<%= booking.room.number %></h2>
    <p>Réservée du <%= booking.start_date %> au <%= booking.end_date %> </p>
    <p>Prix total: <%= booking.total_price %>€</p>
    <%= link_to "Annuler cette réservation", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer cette réservation?"}, class: 'text-danger' %>
  </div>
<% end %>

<h1>Mes réservations passées</h1>
<% @passed_bookings.each do |booking| %>
  <div class="booking-card">
    <h2>Chambre n°<%= booking.room.number %></h2>
    <p>Réservée du <%= booking.start_date %> au <%= booking.end_date %> </p>
    <p>Prix total: <%= booking.total_price %>€</p>
    <%= link_to "Annuler cette réservation", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Voulez-vous supprimer cette réservation?"}, class: 'text-danger' %>
    <%= link_to "Laissez votre avis!", new_booking_review_path(booking) %>
  </div>
<% end %>

<%= link_to "Retourner aux chambres", rooms_path  %>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :rating, label: "Note sur 5"%>
    <%= f.input :comment, label: "Dites-en nous plus!" %>
    <%= f.button :submit, "Confirmer" %>
  <% end %>
</div>

app/views/rooms/_index.html.erb
<div class="room-card-container">
  <% @rooms.each do |room| %>
    <%= link_to room_path(room) do %>

      <div class="room-card">
        <%= image_tag room.image_url%>
        <div class="room-card-infos">
          <div class="description-top">
            <h2>Chambre n°<%= room.number %></h2>
            <p><%= room.price_per_night %>€/nuit</p>
          </div>
          <p><%= room.surface %>m²</p>
          <p><%= room.capacite %> voyageurs</p>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/rooms/index.html.erb
<%= render 'rooms/index', rooms: @rooms %>

app/views/rooms/show.html.erb
<div class="show-container">
  <div class="show-container-top">
    <div class="show-pictures">
      <%= image_tag @room.image_url%>
    </div>

    <div class="booking">
      <div class="room-name">
          Chambre n°<%= @room.number%>
      </div>
      <div class="room-price mt-5">
        <%= @room.price_per_night %>€ par nuit
      </div>
        <div class="booking-form" data-controller="flatpickr">
          <%= simple_form_for [@room, @booking] do |f| %>
            <%= f.input :start_date, as: :string, label: "Dates de réservation", input_html: { data: { flatpickr_target: "startDate" } }, id: 'start_date'%>
            <div class="d-none">
              <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } }, id: 'end_date', disabled: true%>
            </div>
            <%= f.button :submit, "Reserver", class: "custom-button", input_html: { data: { flatpickr_action: "click->flatpickr#addToBookedDates" } } %>
          <% end %>
        </div>
    </div>
  </div>

  <div class="show-container-bottom mt-4 border-bottom border-top pt-3 pb-3">
      <div class="description">
        <h2>Description :</h2>
        <p style="font-size: 25px;"><%= @room.description %></p>
      </div>
  </div>

  <div class="show-reviews">
    <% @room.reviews.each do |review| %>
      <%= review.rating %>
      <%= review.comment %>
    <%end%>
  </div>

</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
  <%= f.search_field :description_i_cont_any,
  placeholder:"Search...",
  class: "form-control me-2"%>
  <%= f.submit "Search!" %>
<% end %>

app/views/search/index.html.erb
<h1>
<%= pluralize(@rooms.count, "Result")%>
</h1>

<%= render 'rooms/index', rooms: @rooms %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to rooms_path, class: "navbar-brand" do %>
      <%= image_tag "home.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        
          <li class="nav-item dropdown">
            <%= render 'search/form' %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", profile_path_url, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              <%= link_to "Messages", "#", class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>